Feature/boton ocultar
jtoledoperez/ProyectoEncuestas pull request #9
Opened 2024-12-02 10:41 UTC by LuisTorFer

Creacion de vistas distintas dentro del index segun un usuario este o no logueado

2024-12-02 11:57 UTC, cpellico-serbatic approved these changes

2024-12-02 11:57 UTC, cpellico-serbatic commented on src/main/webapp/crearPregunta.jsp
> +        <!-- un boton que crea respuestas asociadas a la pregunta -->
no hace falta que comentes todo , un buen codigo es aquel que se autoexplica , usa lo comentarios para componentes complejos o flujos complicados

2024-12-05 13:04 UTC, asotoSerbatic commented on src/main/webapp/index.jsp
> +                <!-- Enlace para iniciar sesiÃ³n que redirige a login.jsp -->
Este comentario es innecesario

2024-12-05 13:05 UTC, asotoSerbatic requested changes

2024-12-05 13:05 UTC, asotoSerbatic commented on src/main/webapp/index.jsp
> +                <!-- Enlace para iniciar sesiÃ³n que redirige a login.jsp -->
Este comentario es innecesario

2024-12-11 09:52 UTC, closed without merging

2024-12-11 09:52 UTC, LuisTorFer commented
Se implemento en otra feature, rama desactualizada.